/**
 * Statistical OT anomaly scorer.
 *
 * Each sensor is compared against an attack-free baseline (per-sensor z-score); the weighted
 * composite is mapped to a 0-100 risk score. All constants come from
 * `src/data/model/scorer-params.json`, generated by `analysis/export_model.py` - nothing is
 * copied by hand between Python and TypeScript.
 *
 * This scorer, not the LLM, decides whether a sample is anomalous. The LLM only explains it.
 */

import params from '@/data/model/scorer-params.json';
import type { SensorContribution } from '@/lib/types';

export type { SensorContribution };

export type SensorReadings = {
  temp: number;
  pressure: number;
  vibration: number;
};

type SensorName = keyof SensorReadings;
type SensorStatus = SensorContribution['status'];

const SENSOR_NAMES = Object.keys(params.sensors) as SensorName[];

export type AnomalyScoreResult = {
  anomaly_score: number;
  risk_score: number;
  status: 'SECURE' | 'CRITICAL';
  per_sensor_contributions: SensorContribution[];
};

function computeZScore(value: number, mean: number, std: number): number {
  return Math.abs((value - mean) / (std + 1e-10));
}

function sensorStatus(z: number, warning: number, critical: number): SensorStatus {
  if (z >= critical) return 'critical';
  if (z >= warning) return 'warning';
  return 'normal';
}

/**
 * Compute anomaly score and risk score for a set of OT sensor readings.
 *
 * Returns:
 *   - anomaly_score: [0.01, 0.99] - squashed max z-score, kept for API compatibility
 *   - risk_score:    [0, 100] - severity from the weighted composite z-score
 *   - status:        'SECURE' | 'CRITICAL' - risk_score >= critical_risk_threshold
 *   - per_sensor_contributions: which sensors drive the score, largest first
 */
export function scoreMetrics(readings: SensorReadings): AnomalyScoreResult {
  const z = {} as Record<SensorName, number>;
  let compositeZ = 0;
  let totalZ = 1e-10;
  let maxZ = 0;
  for (const name of SENSOR_NAMES) {
    const sensor = params.sensors[name];
    z[name] = computeZScore(readings[name], sensor.mean, sensor.std);
    compositeZ += z[name] * sensor.weight;
    totalZ += z[name];
    maxZ = Math.max(maxZ, z[name]);
  }

  const riskScore = Math.round(
    Math.min(100, Math.max(0, 100 * (1 - Math.exp(-params.risk_score_decay * compositeZ))))
  );
  const anomalyScore = parseFloat(
    Math.min(0.99, Math.max(0.01, 1 - Math.exp(-params.anomaly_score_decay * maxZ))).toFixed(3)
  );
  const status = riskScore >= params.critical_risk_threshold ? 'CRITICAL' : 'SECURE';

  const contributions: SensorContribution[] = SENSOR_NAMES.map((name) => ({
    sensor: name,
    z_score: parseFloat(z[name].toFixed(2)),
    contribution_pct: parseFloat(((z[name] / totalZ) * 100).toFixed(1)),
    status: sensorStatus(z[name], params.sensors[name].z_warning, params.sensors[name].z_critical),
  })).sort((a, b) => b.z_score - a.z_score);

  return {
    anomaly_score: anomalyScore,
    risk_score: riskScore,
    status,
    per_sensor_contributions: contributions,
  };
}

/**
 * Generate a human-readable log entry based on sensor contributions.
 */
export function buildLogEntry(
  result: AnomalyScoreResult,
  sourceIp: string,
): string {
  if (result.status === 'CRITICAL') {
    const topSensor = result.per_sensor_contributions[0];
    return (
      `ANOMALY DETECTED — Risk score ${result.risk_score}/100. ` +
      `Primary driver: ${topSensor.sensor} (z=${topSensor.z_score}). ` +
      `Source IP: ${sourceIp}`
    );
  }
  const topAnomalous = result.per_sensor_contributions.find(c => c.status !== 'normal');
  if (topAnomalous) {
    return `Advisory: ${topAnomalous.sensor} at z=${topAnomalous.z_score} — within tolerance, monitoring. IP: ${sourceIp}`;
  }
  return 'Status check OK — all sensors within normal operating envelope.';
}
